### PR TITLE
Supakrit fix 404 page

### PR DESCRIPTION
**Pull request by SupTarr**
- Add new page 404 to be more beautiful

### CODE REVIEW

**Comment by cherieasa** [comment]
image
image

**Comment by cherieasa** [comment]
Perhaps you could make the navigation bar at the top be the same length or style as the other pages (eg. contact us), looks a little weird.

**Comment by SupTarr** [comment]
image
image
Which one you would like to have?

**Comment by cherieasa** [comment]
Prefer top.

**Comment by cherieasa** [comment]
Approved but need to resolve small conflict

**Pull request merged**
