### PR TITLE
Fix navbar width on larger screen

### PR DESCRIPTION
**Pull request by SupTarr**
image
Before
image
After: Fixed navbar's width on larger screen to be more responsive

### CODE REVIEW

**Comment by cherieasa** [comment]
think this looks a bit weird with the logo and buttons floating towards the center of the screen more so than the edge in larger displays. is there a point to make this change, what was the problem with the original design?

**Comment by SupTarr** [comment]
image
On some larger screen they will float far away from each side, So I decide to float on center

**Comment by cherieasa** [comment]
Ah okay thats fine. From a design perspective,  I also think you should move the “Technical partner for startups in Asia” body text to the center too in wider screens so it matches the bottom center component text “our goal is to be the technical partner for startup in Asia”

**Comment by SupTarr** [comment]
I will move the **“Technical partner for startups in Asia”** body text to the center in `supakrit-fix-home-page` branch soon.
For this branch, the task has been finished. @cherieasa

**Comment by cherieasa** [comment]
Ok, let me know when that branch is done. You can fix the merge conflict in this branch too

**Pull request merged**
