### PR TITLE
Supakrit new career title

### PR DESCRIPTION
**Pull request by SupTarr**

### CODE REVIEW

**Comment by SupTarr** [comment]
- Responsive Career detail title on mobile phone 
- Remove padding from contract us to make it not go to new line

**Review by cherieasa — APPROVED** [review]

**Comment by cherieasa** [comment]
image
image
Would be nice if you could make the padding the same when the title of the job is on the second line

**Comment by cherieasa** [comment]
image
Also fix the responsive title if not too much of a hassle

**Comment by SupTarr** [comment]
image

**Pull request merged**
