### PR TITLE
Supakrit

### PR DESCRIPTION
**Pull request by SupTarr**

### CODE REVIEW

**Comment by SupTarr** [comment]
- Correct Home -> 2022
- Add Jobs -> **(Sale + PM)** & **read detail** & **Photo**
- Change Personal Laptop to Hybrid Work
- Add Bettercast section  -> section, photo, tech stack
-

**Comment by cherieasa** [comment]
image
I think it looks weird, since it looks off center (when you dont see the "read details" text on hover), when it is not. Perhaps I think its best if you stuck to the original design and add the 3 months in the page when you click on the button. Or instead bold text/ make it clear in the job description that it is a 3 months contract.

**Comment by SupTarr** [comment]
Move time into career detail
MicrosoftTeams-image (4)

**Comment by cherieasa** [comment]
image
You are missing the 3 months contract information on the career page. 
You can achieve this by:
1 - add 3 months into the headline title or
2 - Add some "Information" text and underneath add - "3 months contract."
Make sure it is clear to reader

**Pull request merged**
